[NbConvertApp] WARNING | pattern '05_04.ipynb\xa0' matched no files
[NbConvertApp] Converting notebook 05_04.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-04-07 10:59:44.602776: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: $/var/lib/docker/overlay2/18478643efb701f8f9328b366f3a90e0c665abd53b5648d82e2f2485dad3916c/merged/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
2024-04-07 10:59:44.602854: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
[NbConvertApp] Converting notebook emotion-detection-bert.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
2024-04-10 18:26:00.799522: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: $/var/lib/docker/overlay2/18478643efb701f8f9328b366f3a90e0c665abd53b5648d82e2f2485dad3916c/merged/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
2024-04-10 18:26:00.799647: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
The current process just got forked. Disabling parallelism to avoid deadlocks...
To disable this warning, please explicitly set TOKENIZERS_PARALLELISM=(true | false)
2024-04-10 18:26:24.956045: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: $/var/lib/docker/overlay2/18478643efb701f8f9328b366f3a90e0c665abd53b5648d82e2f2485dad3916c/merged/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
2024-04-10 18:26:24.956340: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: $/var/lib/docker/overlay2/18478643efb701f8f9328b366f3a90e0c665abd53b5648d82e2f2485dad3916c/merged/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
2024-04-10 18:26:24.956468: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: $/var/lib/docker/overlay2/18478643efb701f8f9328b366f3a90e0c665abd53b5648d82e2f2485dad3916c/merged/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
2024-04-10 18:26:24.962952: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusolver.so.11'; dlerror: libcusolver.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: $/var/lib/docker/overlay2/18478643efb701f8f9328b366f3a90e0c665abd53b5648d82e2f2485dad3916c/merged/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
2024-04-10 18:26:24.963180: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: $/var/lib/docker/overlay2/18478643efb701f8f9328b366f3a90e0c665abd53b5648d82e2f2485dad3916c/merged/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
2024-04-10 18:26:24.963477: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: $/var/lib/docker/overlay2/18478643efb701f8f9328b366f3a90e0c665abd53b5648d82e2f2485dad3916c/merged/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudart.so.11.0
2024-04-10 18:26:24.963500: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1835] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
[NbConvertApp] Converting notebook gasentimentanalysis.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/raid/home/dgx914/.local/bin/jupyter-nbconvert", line 8, in <module>
    sys.exit(main())
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 350, in start
    self.convert_notebooks()
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 524, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 489, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 418, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
    nb_copy, resources = super().from_notebook_node(nb, resources, **kw)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 143, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 318, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 79, in preprocess
    self.execute()
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbclient/client.py", line 560, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 123, in async_execute_cell
    cell, resources = self.preprocess_cell(cell, self.resources, cell_index)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 146, in preprocess_cell
    cell = run_sync(NotebookClient.async_execute_cell)(self, cell, index, store_history=self.store_history)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nest_asyncio.py", line 98, in run_until_complete
    return f.result()
  File "/usr/lib/python3.6/asyncio/tasks.py", line 180, in _step
    result = coro.send(None)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbclient/client.py", line 854, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/raid/home/dgx914/.local/lib/python3.6/site-packages/nbclient/client.py", line 756, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
nlp = spacy.load("en_core_web_sm")
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mOSError[0m                                   Traceback (most recent call last)
[0;32m<ipython-input-1-8d092272a28e>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mnlp[0m [0;34m=[0m [0mspacy[0m[0;34m.[0m[0mload[0m[0;34m([0m[0;34m"en_core_web_sm"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;32m~/.local/lib/python3.6/site-packages/spacy/__init__.py[0m in [0;36mload[0;34m(name, vocab, disable, enable, exclude, config)[0m
[1;32m     55[0m         [0menable[0m[0;34m=[0m[0menable[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[1;32m     56[0m         [0mexclude[0m[0;34m=[0m[0mexclude[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 57[0;31m         [0mconfig[0m[0;34m=[0m[0mconfig[0m[0;34m,[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     58[0m     )
[1;32m     59[0m [0;34m[0m[0m

[0;32m~/.local/lib/python3.6/site-packages/spacy/util.py[0m in [0;36mload_model[0;34m(name, vocab, disable, enable, exclude, config)[0m
[1;32m    470[0m     [0;32mif[0m [0mname[0m [0;32min[0m [0mOLD_MODEL_SHORTCUTS[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    471[0m         [0;32mraise[0m [0mIOError[0m[0;34m([0m[0mErrors[0m[0;34m.[0m[0mE941[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mname[0m[0;34m=[0m[0mname[0m[0;34m,[0m [0mfull[0m[0;34m=[0m[0mOLD_MODEL_SHORTCUTS[0m[0;34m[[0m[0mname[0m[0;34m][0m[0;34m)[0m[0;34m)[0m  [0;31m# type: ignore[index][0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 472[0;31m     [0;32mraise[0m [0mIOError[0m[0;34m([0m[0mErrors[0m[0;34m.[0m[0mE050[0m[0;34m.[0m[0mformat[0m[0;34m([0m[0mname[0m[0;34m=[0m[0mname[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    473[0m [0;34m[0m[0m
[1;32m    474[0m [0;34m[0m[0m

[0;31mOSError[0m: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a Python package or a valid path to a data directory.

